pntt_231220952/Models/ErrorViewModel.cs
namespace pntt_231220952.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

pntt_231220952/Models/PnttComputer.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
namespace pntt_231220952.Models
{
    [Table("pnttComputer")]
    public class PnttComputer
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PnttComId { get; set; }
        [StringLength(200)]
        public string PnttComName { get; set;}
        [Range(100,5000)]
        public double PnttComPrice { get; set; }

        [StringLength(200)]
        public string PnttComImage { get; set;}
        [StringLength(200)]
        public string PnttComStatus { get; set; }
    }
}

pntt_231220952/Models/pnttDBContext.cs
using Microsoft.EntityFrameworkCore;
using pntt_231220952.Models;


namespace pntt_231220952.Models
{
    public class pnttDBContext: DbContext
    {
        public pnttDBContext(DbContextOptions<pnttDBContext>options)
            : base(options) { 
        }
        public DbSet<PnttComputer> pnttComputers { get; set; }
    }
}

pntt_231220952/Controllers/PnttComputersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pntt_231220952.Models;

namespace pntt_231220952.Controllers
{
    public class PnttComputersController : Controller
    {
        private readonly pnttDBContext _context;

        public PnttComputersController(pnttDBContext context)
        {
            _context = context;
        }

        // GET: PnttComputers
        public async Task<IActionResult> pnttIndex()
        {
            return View(await _context.pnttComputers.ToListAsync());
        }

        // GET: PnttComputers/Details/5
        public async Task<IActionResult> pnttDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pnttComputer = await _context.pnttComputers
                .FirstOrDefaultAsync(m => m.PnttComId == id);
            if (pnttComputer == null)
            {
                return NotFound();
            }

            return View(pnttComputer);
        }

        // GET: PnttComputers/Create
        public IActionResult pnttCreate()
        {
            return View();
        }

        // POST: PnttComputers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> pnttCreate([Bind("PnttComId,PnttComName,PnttComPrice,PnttComImage,PnttComStatus")] PnttComputer pnttComputer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pnttComputer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pnttComputer);
        }

        // GET: PnttComputers/Edit/5
        public async Task<IActionResult> pnttEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pnttComputer = await _context.pnttComputers.FindAsync(id);
            if (pnttComputer == null)
            {
                return NotFound();
            }
            return View(pnttComputer);
        }

        // POST: PnttComputers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> pnttEdit(int id, [Bind("PnttComId,PnttComName,PnttComPrice,PnttComImage,PnttComStatus")] PnttComputer pnttComputer)
        {
            if (id != pnttComputer.PnttComId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pnttComputer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PnttComputerExists(pnttComputer.PnttComId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pnttComputer);
        }

        // GET: PnttComputers/Delete/5
        public async Task<IActionResult> pnttDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pnttComputer = await _context.pnttComputers
                .FirstOrDefaultAsync(m => m.PnttComId == id);
            if (pnttComputer == null)
            {
                return NotFound();
            }

            return View(pnttComputer);
        }

        // POST: PnttComputers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> pnttDeleteConfirmed(int id)
        {
            var pnttComputer = await _context.pnttComputers.FindAsync(id);
            if (pnttComputer != null)
            {
                _context.pnttComputers.Remove(pnttComputer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PnttComputerExists(int id)
        {
            return _context.pnttComputers.Any(e => e.PnttComId == id);
        }
    }
}

pntt_231220952/Controllers/pnttHomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using pntt_231220952.Models;

namespace pntt_231220952.Controllers
{
    public class pnttHomeController : Controller
    {
        private readonly ILogger<pnttHomeController> _logger;

        public pnttHomeController(ILogger<pnttHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult pnttIndex()
        {
            return View();
        }

        public IActionResult pnttPrivacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult pnttContact() { 
            return View();
        }
    }
}

pntt_231220952/Views/PnttComputers/pnttCreate.cshtml
@model pntt_231220952.Models.PnttComputer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PnttComputer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PnttComName" class="control-label"></label>
                <input asp-for="PnttComName" class="form-control" />
                <span asp-validation-for="PnttComName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PnttComPrice" class="control-label"></label>
                <input asp-for="PnttComPrice" class="form-control" />
                <span asp-validation-for="PnttComPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PnttComImage" class="control-label"></label>
                <input asp-for="PnttComImage" class="form-control" />
                <span asp-validation-for="PnttComImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PnttComStatus" class="control-label"></label>
                <input asp-for="PnttComStatus" class="form-control" />
                <span asp-validation-for="PnttComStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

pntt_231220952/Views/PnttComputers/pnttDelete.cshtml
@model pntt_231220952.Models.PnttComputer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PnttComputer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PnttComName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PnttComName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PnttComPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PnttComPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PnttComImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PnttComImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PnttComStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PnttComStatus)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PnttComId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

pntt_231220952/Views/PnttComputers/pnttDetails.cshtml
@model pntt_231220952.Models.PnttComputer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PnttComputer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PnttComName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PnttComName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PnttComPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PnttComPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PnttComImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PnttComImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PnttComStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PnttComStatus)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PnttComId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

pntt_231220952/Views/PnttComputers/pnttEdit.cshtml
@model pntt_231220952.Models.PnttComputer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PnttComputer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PnttComId" />
            <div class="form-group">
                <label asp-for="PnttComName" class="control-label"></label>
                <input asp-for="PnttComName" class="form-control" />
                <span asp-validation-for="PnttComName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PnttComPrice" class="control-label"></label>
                <input asp-for="PnttComPrice" class="form-control" />
                <span asp-validation-for="PnttComPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PnttComImage" class="control-label"></label>
                <input asp-for="PnttComImage" class="form-control" />
                <span asp-validation-for="PnttComImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PnttComStatus" class="control-label"></label>
                <input asp-for="PnttComStatus" class="form-control" />
                <span asp-validation-for="PnttComStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

pntt_231220952/Views/PnttComputers/pnttIndex.cshtml
@model IEnumerable<pntt_231220952.Models.PnttComputer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PnttComName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PnttComPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PnttComImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PnttComStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PnttComName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PnttComPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PnttComImage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PnttComStatus)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PnttComId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PnttComId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PnttComId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

pntt_231220952/Views/Shared/_pnttLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pntt_231220952</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pntt_231220952.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pntt_231220952</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="pnttHome" asp-action="pnttIndex">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="pnttHome" asp-action="pnttPrivacy">Privacy</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="pnttHome" asp-action="pnttContact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PnttComputers" asp-action="pnttIndex">PnttComputers</a>

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - pntt_231220952 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

pntt_231220952/Views/pnttHome/pnttIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

pntt_231220952/Views/pnttHome/pnttPrivacy.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

pntt_231220952/Views/pnttHome/pnttcontact.cshtml
@{
    ViewData["Title"] = "Liên hệ cá nhân";
}

<h2>@ViewData["Title"]</h2>
<hr />

<div class="container mt-4">
    <div class="card shadow p-4 rounded-3">
        <h3 class="mb-3 text-primary">Thông tin cá nhân</h3>
        <ul class="list-unstyled">
            <li><strong>Họ và tên:</strong> Phạm Nguyễn Thanh Tùng</li>
            <li><strong>Email:</strong> tungtin201205@gmail.com</li>
            <li><strong>Số điện thoại:</strong> Hà Nội</li>
            <li><strong>Địa chỉ:</strong> Quận </li>
        </ul>

        <h3 class="mt-4 text-success">Liên hệ thêm</h3>
     
    </div>
</div>